version: 2.1

orbs:
  architect: giantswarm/architect@5.11.5

workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-giantswarm-catalog
          context: architect
          executor: app-build-suite
          chart: kuberay
          app_catalog: giantswarm-catalog
          app_catalog_test: giantswarm-test-catalog
          filters:
            branches:
              ignore:
                - main
                - master
            tags:
              only: /^v.*/
